import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:intl/date_symbol_data_local.dart';

import 'src/app.dart';
import 'src/core/constants.dart';
import 'src/features/transactions/domain/transaction_entity.dart';
import 'src/features/budget/domain/budget_limit.dart';
import 'src/features/categories/domain/custom_category.dart';

/// Application entry point
///
/// Initializes:
/// - Hive local database with type adapters
/// - Flutter widgets binding
/// - Intl date formatting for Russian locale
/// - Environment variables
void main() async {
  // Ensure Flutter is initialized before Hive
  WidgetsFlutterBinding.ensureInitialized();

  // Load environment variables
  await dotenv.load(fileName: ".env");

  // Initialize date formatting for Russian locale
  await initializeDateFormatting('en_US', null);

  // Initialize Hive for local storage
  await Hive.initFlutter();

  // Register Hive type adapters
  // Note: These are generated by build_runner from the @HiveType annotations
  // Run: flutter pub run build_runner build
  _registerHiveAdapters();

  // Pre-open boxes for faster first access
  await Hive.openBox<TransactionEntity>(HiveBoxes.transactions);
  await Hive.openBox<BudgetLimit>('budget_limits');
  await Hive.openBox(HiveBoxes.settings);
  await Hive.openBox<CustomCategory>(HiveBoxes.customCategories);

  runApp(const CheckSmartAppWrapper());
}

/// Registers all Hive type adapters
///
/// Must be called before opening any boxes that use these types
void _registerHiveAdapters() {
  // TransactionEntity adapter - generated by hive_generator
  if (!Hive.isAdapterRegistered(HiveTypeIds.transaction)) {
    Hive.registerAdapter(TransactionEntityAdapter());
  }

  // ExpenseCategory adapter
  if (!Hive.isAdapterRegistered(HiveTypeIds.category)) {
    Hive.registerAdapter(ExpenseCategoryAdapter());
  }

  // ReceiptSource adapter
  if (!Hive.isAdapterRegistered(HiveTypeIds.receiptSource)) {
    Hive.registerAdapter(ReceiptSourceAdapter());
  }

  // BudgetPeriod adapter (typeId = 4)
  if (!Hive.isAdapterRegistered(4)) {
    Hive.registerAdapter(BudgetPeriodAdapter());
  }

  // BudgetLimit adapter (typeId = 5)
  if (!Hive.isAdapterRegistered(5)) {
    Hive.registerAdapter(BudgetLimitAdapter());
  }

  // CustomCategory adapter
  if (!Hive.isAdapterRegistered(HiveTypeIds.customCategory)) {
    Hive.registerAdapter(CustomCategoryAdapter());
  }
}

// ============================================================================
// TEMPORARY: Manual Hive adapters
// These should be replaced with generated adapters after running:
// flutter pub run build_runner build
// ============================================================================

/// Hive adapter for TransactionEntity
class TransactionEntityAdapter extends TypeAdapter<TransactionEntity> {
  @override
  final int typeId = HiveTypeIds.transaction;

  @override
  TransactionEntity read(BinaryReader reader) {
    final fields = <int, dynamic>{};
    final numOfFields = reader.readByte();
    for (var i = 0; i < numOfFields; i++) {
      fields[reader.readByte()] = reader.read();
    }
    return TransactionEntity(
      id: fields[0] as String,
      amount: fields[1] as double,
      currency: fields[2] as String? ?? kDefaultCurrency,
      merchant: fields[3] as String?,
      category: fields[4] as ExpenseCategory,
      date: fields[5] as DateTime,
      source: fields[6] as ReceiptSource,
      receiptNumber: fields[7] as String?,
      rawOcrText: fields[8] as String?,
      note: fields[9] as String?,
      createdAt: fields[10] as DateTime,
      customCategoryId: fields[11] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, TransactionEntity obj) {
    writer
      ..writeByte(12)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.amount)
      ..writeByte(2)
      ..write(obj.currency)
      ..writeByte(3)
      ..write(obj.merchant)
      ..writeByte(4)
      ..write(obj.category)
      ..writeByte(5)
      ..write(obj.date)
      ..writeByte(6)
      ..write(obj.source)
      ..writeByte(7)
      ..write(obj.receiptNumber)
      ..writeByte(8)
      ..write(obj.rawOcrText)
      ..writeByte(9)
      ..write(obj.note)
      ..writeByte(10)
      ..write(obj.createdAt)
      ..writeByte(11)
      ..write(obj.customCategoryId);
  }
}

/// Hive adapter for ExpenseCategory enum
class ExpenseCategoryAdapter extends TypeAdapter<ExpenseCategory> {
  @override
  final int typeId = HiveTypeIds.category;

  @override
  ExpenseCategory read(BinaryReader reader) {
    return ExpenseCategory.values[reader.readInt()];
  }

  @override
  void write(BinaryWriter writer, ExpenseCategory obj) {
    writer.writeInt(obj.index);
  }
}

/// Hive adapter for ReceiptSource enum
class ReceiptSourceAdapter extends TypeAdapter<ReceiptSource> {
  @override
  final int typeId = HiveTypeIds.receiptSource;

  @override
  ReceiptSource read(BinaryReader reader) {
    return ReceiptSource.values[reader.readInt()];
  }

  @override
  void write(BinaryWriter writer, ReceiptSource obj) {
    writer.writeInt(obj.index);
  }
}
